= Quarkus Opentelemetry Exporter for Microsoft Azure

include::./includes/attributes.adoc[]

This exporter sends data to the Azure portal.

== General configuration

First, add the https://mvnrepository.com/artifact/io.quarkus/quarkus-opentelemetry[quarkus-opentelemetry extension] to your build file.

After, add the https://mvnrepository.com/artifact/io.quarkiverse.opentelemetry.exporter/quarkus-opentelemetry-exporter-azure[Azure extension] to be able to send the telemetry data to the Azure portal.

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.opentelemetry.exporter</groupId>
    <artifactId>quarkus-opentelemetry-exporter-azure</artifactId>
    <version>{project-version}</version>
</dependency>
----

You also need an Application Insights resource receiving the telemetry data. Go to the Azure portal, search for your Application Insights resource or create a new one. On the overview page of your resource, you will find a connection string https://learn.microsoft.com/azure/azure-monitor/app/sdk-connection-string[in the top right corner].

You have two options to set the connection string, one using the Quarkus naming semantics and the other one using the default naming from the Azure documentation.

To set the connection string with the Quarkus naming semantics:

* With the `application.properties` file

[source]
----
quarkus.otel.azure.applicationinsights.connection.string=your_connection_string
----

* With the `QUARKUS_OTEL_AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING=your_connection_string` environment variable


If you want to use the Azure Application Insights way of specifying the connection string, which takes precedence over the Quarkus way:

* With the `application.properties` file

[source]
----
azure.applicationinsights.connection.string=your_connection_string
----

* With the `AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING=your_connection_string` environment variable


You can disable the Azure export in this way:

[source]
----
quarkus.opentelemetry.tracer.exporter.azure.enabled=false
----

Read https://quarkus.io/guides/opentelemetry#configuration-reference[this page] to learn more configuration options.

== Enable more instrumentation

* Read https://quarkus.io/guides/opentelemetry#jdbc[this documentation] to enable the JDBC instrumentation
* Read https://quarkus.io/guides/opentelemetry#additional-instrumentation[this documentation] to enable additional instrumentations

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-opentelemetry-tracer-exporter-azure.adoc[leveloffset=+1, opts=optional]
