= Quarkus Opentelemetry Exporter for Azure

include::./includes/attributes.adoc[]s.

This exporter sends data to the Azure portal.

== General configuration

First, add the [quarkus-opentelemetry extension](https://mvnrepository.com/artifact/io.quarkus/quarkus-opentelemetry) to your build file.

After, add the [Azure extension](https://mvnrepository.com/artifact/io.quarkiverse.opentelemetry.exporter/quarkus-opentelemetry-exporter-azure) to be able to send the telemetry data to the Azure portal.

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.opentelemetry.exporter</groupId>
    <artifactId>quarkus-opentelemetry-exporter-azure</artifactId>
    <version>{project-version}</version>
</dependency>
----

You also need an Application Insights resource receiving the telemetry data. Go to the Azure portal, search for your Application Insights resource or create a new one. On the overview page of your resource, you will find a connection string [in the top right corner](https://learn.microsoft.com/azure/azure-monitor/app/sdk-connection-string).

You can set the connection string:
* In the `application.properties` file:

[source]
----
quarkus.otel.azure.applicationinsights.connection.string=your_connection_string
----

* Or as an environment variable: `QUARKUS_OTEL_AZURE_APPLICATIONINSIGHTS_CONNECTION_STRING=your_connection_string`

You can disable the Azure export in this way:

[source]
----
quarkus.opentelemetry.tracer.exporter.azure.enabled=false
----

Read [this page](https://quarkus.io/guides/opentelemetry#configuration-reference) to learn more configuration options.

== Enable more instrumentation

* Read [this documentation](https://quarkus.io/guides/opentelemetry#jdbc) to enable the JDBC instrumentation
* Read [this documentation](https://quarkus.io/guides/opentelemetry#additional-instrumentation) to enable additional instrumentations

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-opentelemetry-tracer-exporter-azure.adoc[leveloffset=+1, opts=optional]
